### ISSUE TITLE
Make bodge-util:log-errors able to ignore some conditions

### ISSUE THREAD

**Issue by svetlyak40wt** [borodust/bodge-utilities#1]
For example, it conflicts with `function-cache` system. Cached function throws `FUNCTION-CACHE::CACHED-A-VALUE` condition to make it possible to turn off caching by calling an `ABORT` restart.

However, `bodge-util:log-errors` catches this condition and writes this `WARNING` each time when cached function decides to update cache. This message pollutes log:

```
CL-USER> (function-cache:defcached foo ()
           :foo)
#<FUNCTION-CACHE:THUNK-CACHE NAME:FOO  {1001F6F653}>
CL-USER> (bodge-util:log-errors
           (foo))
 <WARN> [17:09:22] bodge-util utils.lisp (invoke-bodgy h1) -
  Unhandled condition:
Condition FUNCTION-CACHE::CACHED-A-VALUE was signalled.
   [Condition of type FUNCTION-CACHE::CACHED-A-VALUE]

#<ENVIRONMENT {1002E57FE3}>
   [Environment of thread #<THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1003CE3BE3}>]

Available restarts:
 0: [ABORT] Skip caching this value
 1: [RETRY] Retry SLY mREPL evaluation request.
 2: [ABORT] Return to SLY's top level.
 3: [ABORT] abort thread (#<THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1003CE3BE3}>)

Backtrace:
 7: (SB-KERNEL::%SIGNAL Condition FUNCTION-CACHE::CACHED-A-VALUE was signalled.)
 8: ((:METHOD (SETF FUNCTION-CACHE:GET-CACHED-VALUE) :AROUND (T T T)) (FOO) #<THUNK-CACHE NAME:FOO  {1001F6F653}> NIL)
 9: (FUNCTION-CACHE::%INSERT-INTO-CACHE #<THUNK-CACHE NAME:FOO  {1001F6F653}> NIL CACHE-KEY NIL)
:FOO
CL-USER> (foo)
:FOO
CL-USER> (bodge-util:log-errors
           (foo))
:FOO
```

Probably some dynamic variable could be introduced where I can add a `FUNCTION-CACHE::CACHED-A-VALUE` symbol to not log warnings on this type of conditions?

**Comment by borodust** [comment]
Thanks for the thorough report! 
`log-errors` relay conditions in development mode further up the stack. In production mode though, it just logs them (in games, it is sometimes better to skip a wild condition, rather than crash immediately). Meaning, there's little reason to actually add exception to the rule, would be just easier to enable development mode.

That said, I won't recommend using `bodge-utilties` for any purpose in your projects. It's API is tailored for bodge project collection and ain't stable and won't be. I added clarification to the README.
